travis:
  secure:
    BINSTAR_TOKEN: b1sahJ5RklkuqZ9+gZ4Yv/GgGn+sSYToYko8dRv5egYAfimm2aR+1ZZ2shSYCwuu4QH0bvSpHbCFA2mAD3ublMnEchwF0n/XqDNp+vjumdJobf4yhp/aywFISPsg3jUNH+JvI/DHo9TB895LciXHQbwuxJpGXX3IMKHKsN80dnInPRqeeaGN3+GYqeyPcGGUqVy1Oyj38o+q5GCrfrMqi0nT7otVb4cAbjKtVm5odYcw/8DpmbrsO4h1YjVqoO9j7pVvyqJ1zK/eiMyietSAWXd83wDx3qwoKVfjHQzhFNbAjFF7pzRKtc0xoZHVRoJgKISMLgTEQlF0pNSBO0UC4TV2Fnw59Au1/KMBrsm6PPJmT+C3V78UsgG83kdLnGYLt9iL8xsukYFUGR7SQzVxQCnsdnAGXIC1HEFEk8b+fF+heGhDs+RYIrPVR0opAo6n3EwVLZmnU0VASQlNu3x33UQdSKqqk+PsaF4vSVuM8a5UjpDl7RIEsBu2Bgv2T97Uw+V+UbjhKf6oJK1ySD6Zzp5DnhzuKcI32e+GXg4vey5zAm6rR+zbF0+uf/PGEvIxqvw/lffLoYp1ho7lBV3enLWadVwzY7/yBE+d9v5w0kIq/JoVw3LTf50xgf2EteTNEkpADez1z3qB4P8VOsjIkfSdTdZzgplOrSQ/O3XQqBE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
